"""Build a fresh blind G4 listening pack from the final candidate WAVs.

The baseline is the frozen G3 conversation WAV for each item. The candidate
must be generated by benchmark_g1.cjs with --conversation-wav yes on the same
ordered 12 speech stimuli. The root provenance file is private to reviewers.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

try:
    from .g4_listening import prepare as prepare_blind
except ImportError:
    from g4_listening import prepare as prepare_blind


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def prepare(cases: Path, baseline: Path, candidate_run: Path, output: Path) -> dict:
    with cases.open(newline="", encoding="utf-8") as handle:
        items = list(csv.DictReader(handle))
    manifest = json.loads((candidate_run / "manifest.json").read_text())
    baseline_provenance = json.loads((baseline / "provenance.json").read_text())
    baseline_index = {row["item_id"]: row for row in baseline_provenance["clips"] if row["variant"] == "g3"}
    baseline_hashes = {row["source_sha256"] for row in baseline_index.values()}
    if len(items) < 12 or len({item["item_id"] for item in items}) != len(items):
        raise ValueError("need at least 12 unique items")
    rows, clips = [], []
    for index, item in enumerate(items):
        case_id = f"direct-{index:03d}-s1"
        result = json.loads((candidate_run / f"{case_id}.json").read_text())
        if result.get("reference") != item["user_text"] or result.get("case_id") != case_id:
            raise ValueError(f"candidate case order differs at {case_id}")
        candidate_wav = (candidate_run / f"{case_id}-conversation.wav").resolve()
        baseline_wav = (baseline / f"item-{item['item_id']}-g3.wav").resolve()
        if not candidate_wav.is_file() or not baseline_wav.is_file():
            raise FileNotFoundError(case_id)
        old = baseline_index.get(item["item_id"])
        if old is None or digest(baseline_wav) != old["wav_sha256"]:
            raise ValueError(f"baseline WAV hash mismatch: {item['item_id']}")
        rows.append({"item_id": item["item_id"], "category": item["category"],
                     "baseline_wav": str(baseline_wav), "candidate_wav": str(candidate_wav)})
        clips.append({"item_id": item["item_id"], "candidate_sha256": digest(candidate_wav),
                      "baseline_sha256": digest(baseline_wav), "candidate_valid": result.get("valid")})
    if output.exists():
        raise FileExistsError(output)
    staging = candidate_run / "g5-listening-items.csv"
    with staging.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    prepare_blind(staging, output, raters=5, seed=20260930)
    runtime = manifest["health"]["runtime"]
    provenance = {"schema": 1, "candidate_source_sha256": runtime["source_sha256"],
                  "candidate_config_sha256": runtime["config_sha256"],
                  "candidate_stimuli_sha256": manifest["stimuli_sha256"],
                  "baseline_source_sha256": sorted(baseline_hashes),
                  "basis": "synthetic user TTS and Chromium AudioWorklet render clock; no human microphone or real AEC",
                  "clips": clips}
    provenance_file = output / "provenance.json"
    provenance_file.write_text(json.dumps(provenance, ensure_ascii=False, indent=2) + "\n")
    provenance_file.chmod(0o600)
    return {"items": len(items), "candidate_valid": sum(bool(row["candidate_valid"]) for row in clips),
            "candidate_source_sha256": runtime["source_sha256"], "pack": str(output)}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cases", required=True, type=Path)
    parser.add_argument("--baseline", required=True, type=Path)
    parser.add_argument("--candidate-run", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    print(json.dumps(prepare(args.cases, args.baseline, args.candidate_run, args.output), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
